### ISSUE TITLE
Can't find script files

### ISSUE THREAD

**Issue by nicola-masarone** [saramasarone/Running-kallisto-on-Apocrita#1]
Hi Sara,
looking at your page I couldn't find the real script files (namely  _start_kallisto_array.sh_ and _kallisto_bash_array.sh_) in your repository.
I suppose that if you upload the script files github could tag the repository as using bash language and then it could be easier to find your solution.
Ciao
Nicola

**Comment by saramasarone** [comment]
Hi Nicola,
thanks for the feedback! I've changed the repo to reflect your suggestions! 
Ciao
